using CultBot.Data;
using Microsoft.EntityFrameworkCore;

namespace CultBot.Features.Memes;

public class MemeSchemaInitializer
{
    private readonly IDbContextFactory<CultBotDbContext> _contextFactory;

    public MemeSchemaInitializer(IDbContextFactory<CultBotDbContext> contextFactory)
    {
        _contextFactory = contextFactory;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        await using var context = await _contextFactory.CreateDbContextAsync(cancellationToken);
        if (!context.Database.IsRelational())
            return;

        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PostedMemes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "GuildId" numeric(20,0) NOT NULL,
                "ChannelId" numeric(20,0) NOT NULL,
                "DiscordMessageId" numeric(20,0),
                "Source" text NOT NULL DEFAULT 'Tumblr',
                "SourcePostId" text NOT NULL,
                "ImageUrl" text NOT NULL,
                "ImageSha256" text NOT NULL,
                "ScheduledSlotUtc" timestamp with time zone NOT NULL,
                "ScheduledSlotLocal" text NOT NULL,
                "PostedAtUtc" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_PostedMemes" PRIMARY KEY ("Id")
            );
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "PostedMemes"
            ADD COLUMN IF NOT EXISTS "Source" text NOT NULL DEFAULT 'Reddit';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "PostedMemes"
            ADD COLUMN IF NOT EXISTS "SourcePostId" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'PostedMemes'
                        AND column_name = 'RedditPostId'
                ) THEN
                    UPDATE "PostedMemes"
                    SET "SourcePostId" = "RedditPostId"
                    WHERE "SourcePostId" IS NULL OR "SourcePostId" = '';
                END IF;
            END $$;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            UPDATE "PostedMemes"
            SET "SourcePostId" = CONCAT('legacy-', "Id")
            WHERE "SourcePostId" IS NULL OR "SourcePostId" = '';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "PostedMemes"
            ALTER COLUMN "SourcePostId" SET NOT NULL;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "PostedMemes"
            ALTER COLUMN "Source" SET DEFAULT 'Tumblr';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PostedMemes_GuildId_Source_SourcePostId"
            ON "PostedMemes" ("GuildId", "Source", "SourcePostId");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PostedMemes_GuildId_ImageSha256"
            ON "PostedMemes" ("GuildId", "ImageSha256");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PostedMemes_GuildId_ScheduledSlotUtc"
            ON "PostedMemes" ("GuildId", "ScheduledSlotUtc");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_PostedMemes_PostedAtUtc"
            ON "PostedMemes" ("PostedAtUtc");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "MemeRequestUsages" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" numeric(20,0) NOT NULL,
                "GuildId" numeric(20,0) NOT NULL,
                "Username" text NOT NULL DEFAULT '',
                "RequestKind" text NOT NULL DEFAULT 'User',
                "CommandName" text NOT NULL DEFAULT '/meme',
                "RequestedAtUtc" timestamp with time zone NOT NULL,
                "EasternDateKey" text NOT NULL,
                "Result" text NOT NULL,
                "Reason" text NOT NULL,
                "AttemptsToday" integer NOT NULL DEFAULT 0,
                "SuccessfulRequestsToday" integer NOT NULL DEFAULT 0,
                "Source" text,
                "SourcePostId" text,
                "ImageUrl" text,
                "SourcePermalink" text,
                "ImageSha256" text,
                "DiscordMessageId" numeric(20,0),
                "ChannelId" numeric(20,0),
                CONSTRAINT "PK_MemeRequestUsages" PRIMARY KEY ("Id")
            );
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "Username" text NOT NULL DEFAULT '';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "RequestKind" text NOT NULL DEFAULT 'User';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "CommandName" text NOT NULL DEFAULT '/meme';
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "AttemptsToday" integer NOT NULL DEFAULT 0;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "SuccessfulRequestsToday" integer NOT NULL DEFAULT 0;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "Source" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "SourcePostId" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "ImageUrl" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "SourcePermalink" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "ImageSha256" text;
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "DiscordMessageId" numeric(20,0);
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "MemeRequestUsages"
            ADD COLUMN IF NOT EXISTS "ChannelId" numeric(20,0);
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_MemeRequestUsages_CommandName_RequestedAtUtc"
            ON "MemeRequestUsages" ("CommandName", "RequestedAtUtc");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_MemeRequestUsages_UserId_EasternDateKey_Result"
            ON "MemeRequestUsages" ("UserId", "EasternDateKey", "Result");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_MemeRequestUsages_UserId_EasternDateKey_CommandName"
            ON "MemeRequestUsages" ("UserId", "EasternDateKey", "CommandName");
            """, cancellationToken);

        await context.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_MemeRequestUsages_UserId_RequestedAtUtc"
            ON "MemeRequestUsages" ("UserId", "RequestedAtUtc");
            """, cancellationToken);
    }
}
